### ISSUE TITLE
gridsome build failing: 'request is missing a valid API key'

### ISSUE THREAD

**Issue by zacklerner** [spenwall/gridsome-source-google-sheets#8]
Hi @spenwall!

First off, thanks for the awesome plugin. I've been using this successfully in development for some time and have successfully deployed to Netlify on a number of occasions. It wasn't until today that I had noticed that `gridsome build` was failing on Netlify due to the following error:

```
{ Error: The request is missing a valid API key.
    at Gaxios._request (/Users/zack/Sites/lobster-place-wholesale/web/node_modules/gaxios/build/src/gaxios.js:85:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response:
   { config:
      { url:
         'https://sheets.googleapis.com/v4/spreadsheets//values/A1%3AZZ10000',
        method: 'GET',
        paramsSerializer: [Function],
        headers: [Object],
        params: [Object: null prototype] {},
        validateStatus: [Function],
        retry: true,
        responseType: 'json',
        retryConfig: [Object] },
     data: { error: [Object] },
     headers:
      { 'alt-svc':
         'quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000',
        'cache-control': 'private',
        connection: 'close',
        'content-encoding': 'gzip',
        'content-type': 'application/json; charset=UTF-8',
        date: 'Wed, 04 Mar 2020 17:13:28 GMT',
        server: 'ESF',
        'transfer-encoding': 'chunked',
        vary: 'Origin, X-Origin, Referer',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '0' },
     status: 403,
     statusText: 'Forbidden',
     request:
      { responseURL:
         'https://sheets.googleapis.com/v4/spreadsheets//values/A1%3AZZ10000' } },
  config:
   { url:
      'https://sheets.googleapis.com/v4/spreadsheets//values/A1%3AZZ10000',
     method: 'GET',
     paramsSerializer: [Function],
     headers:
      { 'Accept-Encoding': 'gzip',
        'User-Agent': 'google-api-nodejs-client/2.0.4 (gzip)',
        Accept: 'application/json' },
     params: [Object: null prototype] {},
     validateStatus: [Function],
     retry: true,
     responseType: 'json',
     retryConfig:
      { currentRetryAttempt: 0,
        retry: 3,
        httpMethodsToRetry: [Array],
        noResponseRetries: 2,
        statusCodesToRetry: [Array] } },
  code: 403,
  errors:
   [ { message: 'The request is missing a valid API key.',
       domain: 'global',
       reason: 'forbidden' } ] }
```

Curiously enough, `gridsome develop` continues to work, with changes to Sheets data being reflected on my local dev server. As far as troubleshooting goes, I've tried loading up an older project where the configuration hasn't changed and I'm noticing the same error. I've also tried generating a new API key to see if that might do the trick, but no luck unfortunately.

Here's how it's being used in my template:

```
<template>
  <div>
    
    <ProductListGrid :products="$page.inventory.edges" />

  </div>
</template>

<page-query>
query Page {
  metadata {
    sanityOptions {
      projectId
      dataset
    }
  }
  page: sanityAllProductsPage(id: "03ee4075-942e-4f9e-9807-0818cb784f17") {
    title
    heroHeading
    heroSubtitle
    introCopy
  }
  inventory: allLpwInventory(order: ASC) {
    edges {
      node {
        id
        Web_Description
        Web_Category
        Subcategory
        Fresh_or_Frozen
        Farmed_or_Wild
        Certification
        Availability
        Geography
      }
    }
  }
}
</page-query>
```

And here's the sheet just in case it's useful: https://docs.google.com/spreadsheets/d/1Le68Mw3MLv_o3b4FmR1FUdO1IzvN9k8stBFu3mQIZuI/edit?usp=sharing

Let me know if there's anything else you might need on my end. Thanks again!

**Comment by zacklerner** [comment]
Before you spend any time on this, it looks like I may have solved my own issue. Running `gridsome build` locally seems to assume that the NODE_ENV is production and as a result wasn't getting my local development environment variables. I updated the variables on Netlify and now I'm getting a different error unrelated to the plugin.

Sorry for the false alarm!
